### ISSUE TITLE
No data Whisper Database

### ISSUE THREAD

**Issue by bile0026** [20c/vaping#131]
Looking to get some retention with my latency graphs. I setup a plugin for whisper in my vaping config file but it doesn't seem to write any data. No errors when I launch vaping and start pinging. Stumbled through and figured out what I believe are the necessary fields in the plugin config. Can someone validate this or have any pointers on how to get this working?

```
  - name: whisper
    type: whisper
    retention:
      - 60:7d
      - 5m:30d
      - 15m:90d
    path: data/
    filename: whisper_data
    field: latency
```
