### ISSUE TITLE
fping plugin causing growing fping defunct/zombie processes

### ISSUE THREAD

**Issue by mattlan** [20c/vaping#133]
vaping version: 1.4.2
pypy version: 7.3.5 (python 3.7.10)
fping version: 3.10

vaping config:
```
probes:
  - name: latency
    type: std_fping
    output:
      - prometheus
    testing_hosts:
      hosts:
        - host: 1.1.1.1
          name: Cloudflare DNS
plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - prometheus
  - name: prometheus
    type: prometheus
    port: 9090
```

As summary notes, when leveraging the fping plugin I am seeing these continually grow over time until the vaping process eventually dies.
```
root     15904  0.0  0.0      0     0 pts/0    Z    12:39   0:00 [fping] <defunct>
root     15968  0.0  0.0      0     0 pts/0    Z    12:40   0:00 [fping] <defunct>
root     15974  0.0  0.0      0     0 pts/0    Z    12:40   0:00 [fping] <defunct>
root     15979  0.0  0.0      0     0 pts/0    Z    12:40   0:00 [fping] <defunct>
root     15991  0.0  0.0      0     0 pts/0    Z    12:40   0:00 [fping] <defunct>
```

I believe I've resolved this locally by changing [these lines](https://github.com/20c/vaping/blob/master/src/vaping/plugins/fping.py#L150-L155) to this:
```
with self.popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as proc:
    for line in iter(proc.stdout.readline, b""):
        data.append(self.parse_verbose(line.decode("utf-8")))
```

If I get a chance this week will submit a PR, but just noting this in case anyone else runs into this in the meantime.
