### ISSUE TITLE
Crash after running for several days

### ISSUE THREAD

**Issue by mattlan** [20c/vaping#134]
vaping version: 1.4.2
pypy version: 7.3.5 (python 3.7.10)
fping version: 3.10

vaping config:
```
probes:
  - name: latency
    type: std_fping
    output:
      - prometheus
    testing_hosts:
      hosts:
        - host: 1.1.1.1
          name: Cloudflare DNS
        # few internal hosts omitted
plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - prometheus
  - name: prometheus
    type: prometheus
    port: 9090
```

After running fine for several days, crashes and outputs the following exception:
```
vaping.daemon 'NoneType' object has no attribute 'get' daemon.py:214
PidFile <pid.posix.PidFile object at 0x00007fe8501e2560> closing pidfile: /root/vaping.pid base.py:220
vaping.daemon stopping prometheus daemon.py:254
vaping.daemon stopping latency daemon.py:254
PidFile <pid.posix.PidFile object at 0x00007fe8501e2560> closing pidfile: /root/vaping.pid base.py:220
```

Has currently happened twice now, but since I normally redirect all the debug output (due to #88) I was not able to get the exception output for the prior crash.  Restarted it again and will continue logging the debug output for now.
