### ISSUE TITLE
(vodka? graphsrv?) javascript error "Uncaught TypeError: this.data[0] is undefined" 

### ISSUE THREAD

**Issue by mozai** [20c/vaping#140]
vaping, version 1.4.3, fping: Version 5.0

## Steps to reproduce:
- `fping` already installed
- `pip install -U vaping`
- `mkdir -p ~/.vaping`
- `wget -q -O ~/.vaping/config.yml https://raw.githubusercontent.com/20c/vaping/master/examples/standalone_dns/config.yml`
- edit ~/.vapinig/config.yaml to change 
  - plugins entry "std_fping add a new key for `period: 500`, as the default 20ms is way too short for remote targets
  - probes[0].groups to

```
- name: LAN
  hosts: 
  - {host: "192.168.1.1", name: gateway, color: red}
- name: Remote
  hosts: 
  - {host: "8.8.8.8", name: Equius, color: blue}  
  - {host: "140.82.112.4", name: Kanaya, color: green}
```
- `vaping start`
- point a webbrowser at http://127.0.0.1:7021

## Expected to see:
- graphs updating.  (Would be nice to set the refresh time.  default interval for fping plugin is 1m but seems like graphsrv (flask?) is refreshing much more often than that)

## What I saw instead:
- screenshot https://i.imgur.com/KBSZ60i.jpg
- javascript error every three seconds:

```
     Uncaught TypeError: this.data[0] is undefined
        render_data http://localhost:7021/static/graphsrv/js/graphsrv.smokestack.js:20
        render_dynamic http://localhost:7021/static/graphsrv/js/graphsrv.js:1356
        update http://localhost:7021/static/graphsrv/js/graphsrv.js:983
        _update http://localhost:7021/static/graphsrv/js/graphsrv.js:1107
      ...
```

- graphs get a red error message on them frequently that says "Data Feed Stopped"
