### ISSUE TITLE
Multiple Groups Not Working

### ISSUE THREAD

**Issue by rannday** [20c/vaping#171]
I built a config based off the standalone example. Below is the code section I altered. Pretty simple. Nothing's showing up in its box on the web page. The "public_dns" group still works fine.  I can ping the custom hosts I added from the device I'm testing with. 

What am I missing?

```
groups:
  - name: public_dns
	hosts:
	  - host: 8.8.8.8
		name: Google
		color: red
	  - host: 4.2.2.1
		name: Level(3)
		color: blue
	  - host: 208.67.222.222
		name: OpenDNS
		color: orange

  - name: group2
	hosts:
	  - host: x.x.x.x
		name: host1
		color: red
	  - host: x.x.x.x
		name: host2
		color: blue
	  - host: x.x.x.x
		name: host3
		color: orange
```
