### ISSUE TITLE
Emit doesn't happen when using multiple probe plugins in vaping 1.5.3

### ISSUE THREAD

**Issue by csksudhir** [20c/vaping#172]
We have an environment where we upgraded from vaping version 1.3.0 (Python 3.6) to vaping version 1.5.3 (Python 3.9.16, RHEL 9). After the upgrade, we see that there is a problem with the plugins that we were using. 

We have a total of 3 probe plugins derived from vaping.plugins.TimedProbe all of which output to a common emit plugin derived from vaping.plugins.EmitBase. This combination used to work well in vaping 1.3.0. However in vaping 1.5.3, the output from only one of the probe plugins is being emitted. The output of the other two probe plugins is not emitted even though output is queued as per the log from the framework. 

There is no issue with the probe or the emit plugins itself since if there is only one probe plugin specified in the config file, then its output is emitted.

Could you please let us know if there is any known limitation in having multiple probe plugins in vaping 1.5.3 and if they can use a common emit plugin. 

Here's a snippet of the config.yaml: 

```
probes:
  - name: fping
    type: std_fping
    output:
      - fping_packet
    region1:
      hosts:
        - host: 1.2.3.4
          name: test-vm1
        - host: 1.2.3.5
          name: testvm2
  - name: httping
    type: std_httping
    output:
      - httping_packet
    non-vsi:
      hosts:
        - host: 1.2.3.4
          name: test-vm1
          proto: http
          port: 4318
          path: /tmp/file.txt
        - host: 1.2.3.5
          name: test-vm2
          proto: http
          port: 80
          path: /tmp/file.txt
plugins:
  - name: std_fping
    type: fping
  - name: fping_packet
    type: all_emit
  - name: std_httping
    type: httping
  - name: httping_packet
    type: all_emit
```
