### ISSUE TITLE
Allow vaping probes with same name as plugins, or error?

### ISSUE THREAD

**Issue by vegu** [20c/vaping#37]
Vaping probes are just plugins, and since the name of a plugin is used to store it, currently there is a conflict with a config like this:

```
probes:
  # same name as plugin
  - name: mtr
    type: mtr
    output:
      - vodka

    host: 1.1.1.1

plugins:
  # same name as probe 
  - name: mtr
    type: fping_mtr
    count: 3
    interval: 3s
```

Vaping currently does not raise an error with this setup, but will not work as expected either as the probe will never be instantiated with the new config since a plugin with the same name already exists.
