### ISSUE TITLE
move plugin groups to under `groups` key

### ISSUE THREAD

**Issue by grizz** [20c/vaping#44]
Instead of
```yaml
    public_dns:
      hosts:
```

it should be nested under `groups` like

```yaml
    groups:
      - name: public_dns
        hosts:
```

to allow for future config that may conflict with existing group names
