### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by paulkappler** [20c/vaping#7]
Do you have any ideas on how to get ipv6 support?   It looks like you would need to use fping6.

**Comment by grizz** [comment]
It looks like their options are exactly the same, so you should be able to override the command in your config, for example:

```yaml
plugins:
  - name: fping6
    type: fping
    command: fping6
    count: 10
    interval: 3s
```
